### ISSUE TITLE
q=last on media endpoint

### ISSUE THREAD

**Issue by dshanske** [indieweb/micropub-extensions#10]
@aaronpk implemented this in his endpoint and in Quill. 

It returns a url property only.

When I implemented it, discovered that his implementation

- Only returns images

- Only media uploaded in the last 5 minutes

Brainstorming on iterating the last command with some modifiers

To start, a type modifier

type = all, video, audio, photo - defaults to photo

**Comment by dshanske** [comment]
The second question is, should media in the last five minutes be the expected default behavior? Should last mean last?

**Comment by EdwardHinkle** [comment]
I added this to the [Micropub Extensions page as a proposed extension](https://indieweb.org/Micropub-extensions#Last_Uploaded_Query) so people can find this discussion easier.

**Comment by RosemaryOrchard** [comment]
I would say if the media wasn't uploaded in the last hour I would prefer to not have it attached. 5 minutes might be too short of a time - but last image ever uploaded has been confusing me.

**Comment by dshanske** [comment]
At the Micropub Pop-up Session 2020, it was decided to sunset q=last in favor of q=source&limit=1, see #14
