### ISSUE TITLE
Stable Property: Post Status

### ISSUE THREAD

**Issue by EdwardHinkle** [indieweb/micropub-extensions#19]
[Wiki Page](https://indieweb.org/Micropub-extensions#Post_Status)

This is the idea of adding a new property called post-status that allows you to set a post as published or draft.

post-status=published (or no post-status set) - The post is published, or when the published date is in the future, the post is scheduled.
post-status=draft - The post is a draft, and should not be shown in lists. (Of course it's up to the implementation whether it wants to use a capability URL for draft posts or actually restrict it to logged-in users.)

There are a growing number of clients and servers where this property might be considered stable:

Clients:
- Quill
- Indigenous for Android (supports Draft, Published and Future Dates)
- Micro.blog (supports Draft and Published)

Servers
- p3k
- Micropub for WordPress (supports Draft, Published and Future Dates)
- IndieWeb for Drupal (supports Draft, Published and Future Dates)
- Postr (supports Draft and Published) [also uses post-status=deleted]
- Micro.blog (supports Draft and Published)
- abode (supports Draft and Published)

There are a handful of things in this proposal and I don't think all of them are implemented across all servers and clients, so we probably need to get a agreement on what is being used and what is not.

post-status=published (show now)
post-status=draft (don't show)
post-status=published + published=future date (show in the future)
post-status=deleted (don't show)

I think post-status=deleted is only being used by Postr and duplicates [existing Micropub delete functionality](https://micropub.net/draft/#delete) so I think post-status=deleted will probably be removed from this proposed extension for lack of implementation.

I think everyone on the list incorporates both post-status=published and post-status=draft. The big question is if post-status=published + published=future date should be part of this extension or a different extension regarding "future posts". So I think the main discussion below should be trying to resolve "which of the clients/servers" above actually support future posts.

**Comment by EdwardHinkle** [comment]
@manton @dshanske @aaronpk @swentel

Of your projects listed above as implementations of the Post Status Micropub property, which ones actually support "Future Dated Posts" that is sending a Micropub post with a future "published" date and have it scheduled to not appear until that time has arrived.

**Comment by grantcodes** [comment]
I had future scheduled posts on my old site (need to reimplement them in postr) and all I did for that is send a future published date.

Together & PostrChild also both support publishing with `post-status=draft` 

Also draft doesn't always mean don't show, there are plenty of people who will write public drafts, and leave them unindexed / unlisted until they are ready.

And RE me using `post-status=deleted` it effectively becomes a trash of sorts, so the posts still exist and can be undeleted. I agree it probably shouldn't be in the spec, just a note on my handling on deleting and undeleting posts.

Although now that I have written that it would be pretty cool if a micropub client could query to find deleted posts. But probably quite a niche feature.

**Comment by dshanske** [comment]
Micropub for WordPress does because WordPress does

**Comment by swentel** [comment]
Drupal supports published / draft + future dates. Indigenous allows sending published/draft and future dates (also in draft state) - and also has local drafts.

**Comment by sonnyp** [comment]
I'm a bit concerned about this.

As a user if a client offers me the option to publish a draft, I expect the server not to show them. However, non compatible servers will list/display the post and it might have security/privacy implications.

**Comment by sonnyp** [comment]
An other suggestion is for clients to check server support first using https://indieweb.org/Micropub-extensions#Query_for_Supported_Properties.2FQueries

**Comment by manton** [comment]
Micro.blog supports post-status for drafts, but nothing for future posts yet. I had planned to let a date in the future be enough of a clue, regardless of whether post-status has a value. The behavior seems implementation-specific, unless we want clients to be able to query whether they can rename buttons to say "Schedule" instead of "Publish".

**Comment by EdwardHinkle** [comment]
@manton I agree, I don’t think “Future posts” really belong as part of this Extension, but before I came around someone had put it on the wiki as part of the same thing. So I am essentially just hoping to verify that the in fact, others feel they are different enough and that there is Software (like Micro.blog) that HAS added drafts support but has NOT added future date support. I’ll document the discussions so far in the original list and see where we end up.

**Comment by EdwardHinkle** [comment]
@aaronpk I think you’re the last implementer of this Extension that hasn’t provided their thoughts. Any thoughts? 🙂

**Comment by manton** [comment]
To follow up on this… I realized recently that Micro.blog "accidentally" supports future posts, sort of. If you create a post with a date in the future, it will be published when that date hits, _after_ the next time you create another post or change anything else on your blog.

I plan to tweak this to be a formal "scheduled posts" feature without any other Micropub changes except setting a published date in the future.

**Comment by dshanske** [comment]
Closing this issue as stable. Any discussion of additional post status properties can occur in a new issue linked to this one.

**Comment by jamietanna** [comment]
Do we have an example of what this looks like for:

- JSON Create
- JSON Update

Or is this only expected to be for forms?

**Comment by jamietanna** [comment]
To answer my own question, yes, it is treated as a property `post-status`:

```json
{
  "action": "update",
  "replace": {
    "content": [
      "..."
    ],
    "name": [
      "Reply to https://twitter.com/joshghent/status/1358869174307725316"
    ],
    "post-status": [
      "draft"
    ]
  },
  "url": "https://www.jvt.me/mf2/2021/02/auyd3/"
}
```
