### ISSUE TITLE
Filter returned list of items with limit parameter

### ISSUE THREAD

**Issue by dshanske** [indieweb/micropub-extensions#35]
Similar to #34, in any query that returns a list, this will limit it to x number of returned items.

**Comment by dshanske** [comment]
Discussed at https://indieweb.org/2020/Pop-ups/Micropub. This seems to have consensus and needs documented implementations.

**Comment by dshanske** [comment]
I apparently already supported this.

**Comment by dshanske** [comment]
3:3 implementation requirement satisfied, the extension of limit being added to any query is therefore stable.

**Comment by paulrobertlloyd** [comment]
This query parameter is supported by [Indiekit](https://getindiekit.com).
